---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
  namespace: camunda
spec:
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda
          image: camunda/camunda-bpm-platform:latest
          env:
            - name: DB_DRIVER
              value: org.postgresql.Driver
            - name: DB_URL
              value: jdbc:postgresql://pgsql.postgres.svc.cluster.local:5432/camunda
            - name: DB_USERNAME
              value: pgsql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: camunda
                  key: password
            - name: WAIT_FOR
              value: pgsql.postgres.svc.cluster.local:5432
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: camunda
  namespace: camunda
spec:
  selector:
    app: camunda
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: camunda
  namespace: camunda
type: Opaque
data:
  password: MTIzMTIz  # Base64 encoded value of "123123"
