---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
  namespace: camunda
spec:
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      volumes:
        - name: server
          configMap:
            name: server
            defaultMode: 420
      containers:
        - name: camunda
          image: camunda/camunda-bpm-platform:latest
          env:
            - name: DB_DRIVER
              value: com.mysql.cj.jdbc.Driver
            - name: DB_URL
              value: jdbc:mysql://mysql.mysql.svc.cluster.local:3306/camunda
            - name: DB_USERNAME
              value: mysql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: camunda
                  key: password
            - name: WAIT_FOR
              value: pgsql.postgres.svc.cluster.local:5432
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /camunda/conf/server.xml
              name: server
              subPath: server.xml
---
apiVersion: v1
kind: Service
metadata:
  name: camunda
  namespace: camunda
spec:
  selector:
    app: camunda
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: camunda
  namespace: camunda
type: Opaque
data:
  password: MTIzMTIz  # Base64 encoded value of "123123"
